version: "3"
services:
  mongo:
    image: mongo:3.6
    #container_name: "proxy_mongo"
  pg:
    image: postgres:10
    #container_name: "proxy_pg"
    environment:
      POSTGRES_USER: josh
      POSTGRES_PASSWORD: ebrustej
      POSTGRES_DB: menus
  menu_component:
    image: enaqbz/menu:latest
    #container_name: "proxy_menu_component"
    command: node ./server/index.js 
    links:
      - pg
    depends_on:
      - pg
    deploy:
      resources:
        limits:
          cpus: '0.10'
  map_component:
    image: enaqbz/map:latest
    #container_name: "proxy_map_component"
    command: node ./server/index.js
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.10'
  reviews_component:
    image: enaqbz/reviews
    #container_name: "proxy_reviews_component"
    command: node ./server/server.js
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      DB: mongodb://mongo/
    deploy:
      resources:
        limits:
          cpus: '0.10'
  reservations_component:
    image: enaqbz/reservations
    #container_name: "proxy_reservations_component"
    command: node ./server/index.js
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.10'
  suggested_component:
    image: enaqbz/suggested
    #container_name: "proxy_suggested_component"
    command: node ./server/index.js
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.10'
  nginx:
    image: enaqbz/proxy_nginx
    #container_name: "proxy_nginx"
    command: ./scripts/restore_mongo.sh
    ports:
     - "80:8080"
    depends_on:
      - reviews_component
      - map_component
      - menu_component
      - reservations_component
      - mongo
      - pg

